name = "PackmolInputCreator"
uuid = "6bedda7c-f7fc-48fa-a9d6-96caf740a458"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]
version = "1.0.0-DEV"

[deps]
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
PDBTools = "0.15"
TestItems = "0.1.1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[targets]
test = ["Test", "TestItemRunner", "PDBTools", "DelimitedFiles"]
